version: '2'

services:
    consul:
        image: bhuisgen/alpine-consul
        ports:
            - "8500:8500"
        volumes:
            - /etc/localtime:/etc/localtime:ro
        environment:
            - CONSUL_OPTIONS=-server -bootstrap-expect 1 -client 0.0.0.0 -ui    # minimal server options

    zabbix-agent:
        depends_on:
            - consul
        image: bhuisgen/alpine-zabbix-agent
        network_mode: host
        volumes:
            - /etc/localtime:/etc/localtime:ro
            - /:/rootfs:ro
            - /var/run/docker.sock:/var/run/docker.sock
        environment:
            - CONSUL_AGENT=consul                                               # consul agent hostname/IP
            #- CONSUL_PORT=8500                                                 # consul agent port
            #- CONSUL_KEYPREFIX=path/prefix/                                    # consul key prefix path
            - CONSUL_SERVICENAME=zabbix-agent                                   # consul service name
            - CONSUL_SERVICETAGS=dev                                            # consul service tag
            - CONSUL_SERVICEPORT=10050                                          # consul service port
            - CONSUL_CHECKTYPE=tcp                                              # consul health check type
            #- ZABBIX_ENABLEREMOTECOMMANDS=0                                    # enable remote commands execution
            #- ZABBIX_LOGREMOTECOMMANDS=0                                       # log remote commands
            - ZABBIX_SERVER=172.16.0.1                                          # zabbix server IP/host
            - ZABBIX_HOSTNAME=zabbix-agent                                      # zabbix agent hostname
            #- ZABBIX_HOSTMETADATA=                                             # zabbix agent host metadata
            - ZABBIX_STARTAGENTS=1                                              # number of processes for passive checks
            #- ZABBIX_REFRESHACTIVECHECKS=120                                   # time between active checks refresh
            #- ZABBIX_BUFFERSEND=5                                              # time to keep data in buffer
            #- ZABBIX_BUFFERSIZE=100                                            # maximum number of values in buffer before sending
            #- ZABBIX_MAXLINESPERSECOND=20                                      # maximum number of new lines to send per second
            #- ZABBIX_TIMEOUT=3                                                 # timeout of processing
            #- ZABBIX_UNSAFEUSERPARAMETERS=                                     # enable unsafe user parameters
            #- ZABBIXDOCKER=0                                                   # enable docker monitoring
            #- ZABBIXDOCKERLOG=0                                                # enable logging
            #- ZABBIXDOCKERLOGLEVEL=error                                       # log level
            #- ZABBIXDOCKER_CONTAINERS=0                                        # enable containers metrics
            #- ZABBIXDOCKER_CONTAINERSSTATS=0                                   # enable containers statistics metrics
            #- ZABBIXDOCKER_CONTAINERSTOP=0                                     # enable containers processes metrics
            #- ZABBIXDOCKER_CONTAINERSREMOTE=0                                  # enable containers remote command execution
            #- ZABBIXDOCKER_CONTAINERSREMOTEPATH=/etc/zabbix/scripts/trapper    # remote commands path
            #- ZABBIXDOCKER_CONTAINERSREMOTEDELAY=1                             # remote commands delay
            #- ZABBIXDOCKER_EVENTS=0                                            # enable events metrics
